/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecommendedRouteImport } from './routes/recommended'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MembersRouteImport } from './routes/members'
import { Route as MeetupsRouteImport } from './routes/meetups'
import { Route as DiscountsRouteImport } from './routes/discounts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApprovedRouteImport } from './routes/approved'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecommendedSlugRouteImport } from './routes/recommended.$slug'
import { Route as ApprovedSlugRouteImport } from './routes/approved.$slug'

const RecommendedRoute = RecommendedRouteImport.update({
  id: '/recommended',
  path: '/recommended',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetupsRoute = MeetupsRouteImport.update({
  id: '/meetups',
  path: '/meetups',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscountsRoute = DiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovedRoute = ApprovedRouteImport.update({
  id: '/approved',
  path: '/approved',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendedSlugRoute = RecommendedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RecommendedRoute,
} as any)
const ApprovedSlugRoute = ApprovedSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApprovedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approved': typeof ApprovedRouteWithChildren
  '/auth': typeof AuthRoute
  '/discounts': typeof DiscountsRoute
  '/meetups': typeof MeetupsRoute
  '/members': typeof MembersRoute
  '/privacy': typeof PrivacyRoute
  '/recommended': typeof RecommendedRouteWithChildren
  '/approved/$slug': typeof ApprovedSlugRoute
  '/recommended/$slug': typeof RecommendedSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approved': typeof ApprovedRouteWithChildren
  '/auth': typeof AuthRoute
  '/discounts': typeof DiscountsRoute
  '/meetups': typeof MeetupsRoute
  '/members': typeof MembersRoute
  '/privacy': typeof PrivacyRoute
  '/recommended': typeof RecommendedRouteWithChildren
  '/approved/$slug': typeof ApprovedSlugRoute
  '/recommended/$slug': typeof RecommendedSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/approved': typeof ApprovedRouteWithChildren
  '/auth': typeof AuthRoute
  '/discounts': typeof DiscountsRoute
  '/meetups': typeof MeetupsRoute
  '/members': typeof MembersRoute
  '/privacy': typeof PrivacyRoute
  '/recommended': typeof RecommendedRouteWithChildren
  '/approved/$slug': typeof ApprovedSlugRoute
  '/recommended/$slug': typeof RecommendedSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/approved'
    | '/auth'
    | '/discounts'
    | '/meetups'
    | '/members'
    | '/privacy'
    | '/recommended'
    | '/approved/$slug'
    | '/recommended/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/approved'
    | '/auth'
    | '/discounts'
    | '/meetups'
    | '/members'
    | '/privacy'
    | '/recommended'
    | '/approved/$slug'
    | '/recommended/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/approved'
    | '/auth'
    | '/discounts'
    | '/meetups'
    | '/members'
    | '/privacy'
    | '/recommended'
    | '/approved/$slug'
    | '/recommended/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApprovedRoute: typeof ApprovedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DiscountsRoute: typeof DiscountsRoute
  MeetupsRoute: typeof MeetupsRoute
  MembersRoute: typeof MembersRoute
  PrivacyRoute: typeof PrivacyRoute
  RecommendedRoute: typeof RecommendedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recommended': {
      id: '/recommended'
      path: '/recommended'
      fullPath: '/recommended'
      preLoaderRoute: typeof RecommendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetups': {
      id: '/meetups'
      path: '/meetups'
      fullPath: '/meetups'
      preLoaderRoute: typeof MeetupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discounts': {
      id: '/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof DiscountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approved': {
      id: '/approved'
      path: '/approved'
      fullPath: '/approved'
      preLoaderRoute: typeof ApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommended/$slug': {
      id: '/recommended/$slug'
      path: '/$slug'
      fullPath: '/recommended/$slug'
      preLoaderRoute: typeof RecommendedSlugRouteImport
      parentRoute: typeof RecommendedRoute
    }
    '/approved/$slug': {
      id: '/approved/$slug'
      path: '/$slug'
      fullPath: '/approved/$slug'
      preLoaderRoute: typeof ApprovedSlugRouteImport
      parentRoute: typeof ApprovedRoute
    }
  }
}

interface ApprovedRouteChildren {
  ApprovedSlugRoute: typeof ApprovedSlugRoute
}

const ApprovedRouteChildren: ApprovedRouteChildren = {
  ApprovedSlugRoute: ApprovedSlugRoute,
}

const ApprovedRouteWithChildren = ApprovedRoute._addFileChildren(
  ApprovedRouteChildren,
)

interface RecommendedRouteChildren {
  RecommendedSlugRoute: typeof RecommendedSlugRoute
}

const RecommendedRouteChildren: RecommendedRouteChildren = {
  RecommendedSlugRoute: RecommendedSlugRoute,
}

const RecommendedRouteWithChildren = RecommendedRoute._addFileChildren(
  RecommendedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApprovedRoute: ApprovedRouteWithChildren,
  AuthRoute: AuthRoute,
  DiscountsRoute: DiscountsRoute,
  MeetupsRoute: MeetupsRoute,
  MembersRoute: MembersRoute,
  PrivacyRoute: PrivacyRoute,
  RecommendedRoute: RecommendedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
